/**
 * Checks for the Word guide (run after build-docx and preview-docx).
 * Usage: node scripts/check-docx.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { execFileSync } from 'node:child_process';
import * as C from '../src/content.mjs';

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'output');
const results = [];
const ok = (name, pass, detail = '') => results.push({ name, pass, detail });
const unzip = (f, part) => execFileSync('unzip', ['-p', f, part.replace(/[[\]]/g, '\\$&')], { encoding: 'utf8', maxBuffer: 64 << 20 });
const list = (f) => execFileSync('unzip', ['-Z1', f], { encoding: 'utf8' }).trim().split('\n');

const files = { th: 'CoeFont_Participant_Guide_TH.docx', ja: 'CoeFont_Participant_Guide_TH-JA.docx' };
for (const [v, name] of Object.entries(files)) {
  const f = path.join(OUT, name);
  const parts = list(f).filter((p) => /\.(xml|rels)$/.test(p));
  const all = parts.map((p) => unzip(f, p)).join('\n');
  const doc = unzip(f, 'word/document.xml');
  const core = unzip(f, 'docProps/core.xml');

  const trace = all.match(/claude|anthropic|chromium|playwright|libreoffice|docx-js|generated by|要確認/gi);
  ok(`[${v}] 作成ツール名・要確認の表記がない`, !trace, trace ? [...new Set(trace)].join(', ') : '');
  ok(`[${v}] 作成者が髙山浩和`, /<dc:creator>髙山浩和<\/dc:creator>/.test(core) && /<cp:lastModifiedBy>髙山浩和</.test(core));
  const thaiRuns = [...doc.matchAll(/<w:r>(?:(?!<\/w:r>).)*[฀-๿](?:(?!<\/w:r>).)*<\/w:r>/gs)].map((m) => m[0]);
  const badFont = thaiRuns.filter((r) => !/w:cs="Leelawadee UI"/.test(r) || !/w:bidi="th-TH"/.test(r));
  ok(`[${v}] タイ語の全文字列に複合文字体系フォント（Leelawadee UI）とタイ語の言語指定`, badFont.length === 0,
     `${thaiRuns.length} 箇所中 ${badFont.length} 箇所が未設定`);
  const media = list(f).filter((p) => p.startsWith('word/media/') && !p.endsWith('/'));
  ok(`[${v}] 画面コピー4点が埋め込まれている`, media.length === 4, `${media.length} 点`);
  const hasJa = /[぀-ヿ]{6,}/.test(doc.replace(/ブラウザで開く|チャットに再送/g, ''));
  ok(`[${v}] 日本語の本文は${v === 'ja' ? '含む' : '含まない（ボタン名のみ）'}`, v === 'ja' ? hasJa : !hasJa);
}

// The labels quoted in the guide are the product's own UI text (participant page i18n, checked 2026-09-24)
const PRODUCT = {
  th: ['เริ่มพร้อมเสียง', 'เริ่มด้วยข้อความเท่านั้น', 'ไม่พบการประชุม กรุณาตรวจสอบ URL', 'เชื่อมต่อไม่สำเร็จ', 'การประชุมยังไม่เริ่ม'],
  en: ['Continue With Audio', 'Continue With Text Only', 'Meeting not found. Please check the URL.', 'Connection failed', 'This meeting has not started yet'],
};
const text = JSON.stringify(C);
const missing = [...PRODUCT.th, ...PRODUCT.en].filter((s) => !text.includes(s));
ok('画面の表示文言（タイ語・英語）が製品の表記と一致', missing.length === 0, missing.join(' | '));

// Cross references inside the text
const stepNos = C.steps.items.map((s) => s.n);
const qrStep = C.steps.items.find((s) => s.image?.file === 'pc_01_link.png')?.n;
ok('本文中の手順番号の参照が正しい（QRの図＝手順2、手順3〜5が存在）',
   qrStep === 2 && [3, 4, 5].every((n) => stepNos.includes(n)) && /ขั้นตอนที่ 2/.test(C.smartphone.items[0].th));
ok('英語の定型フレーズが両方向とも載っている', C.phrases.groups.length === 2 && C.phrases.groups.every((g) => g.rows.length > 0),
   C.phrases.groups.map((g) => `${g.label.en}: ${g.rows.length}`).join(' | '));
ok('スマートフォンでの使い方の説明がある', C.smartphone.items.length >= 3);

// Preview page count (LibreOffice with stand-in fonts; Word may differ slightly)
const pdf = path.join(ROOT, 'preview', 'CoeFont_Participant_Guide_TH.pdf');
if (fs.existsSync(pdf)) {
  const pages = Number(execFileSync('pdfinfo', [pdf], { encoding: 'utf8' }).match(/Pages:\s+(\d+)/)[1]);
  ok('タイ語版がA4で3ページ以内（プレビュー）', pages <= 3, `${pages} ページ`);
}
const par = path.join(OUT, 'TH-EN-JA_parallel_text.txt');
ok('対訳一覧を出力した', fs.existsSync(par) && /^TH: /m.test(fs.readFileSync(par, 'utf8')));

console.log('\n検品結果\n' + '='.repeat(60));
for (const r of results) console.log(`${r.pass ? '[OK]' : '[NG]'}  ${r.name}${r.detail ? `\n        ${r.detail}` : ''}`);
const ng = results.filter((r) => !r.pass).length;
console.log('='.repeat(60) + `\n${results.length - ng}/${results.length} 項目クリア`);
process.exit(ng ? 1 : 0);
